export const PLANES = [
  {
    nombre: 'Sentinel Mini',
    slug: 'mini',
    maxCondominios: 3,
    precioMensual: 40.00,
    moneda: 'PEN',
    caracteristicas: [
      'Hasta 3 condominios',
      'Gestión de unidades',
      'Control de personal',
      'Recibos mensuales',
      'Soporte por email',
    ],
  },
  {
    nombre: 'Sentinel Start',
    slug: 'start',
    maxCondominios: 5,
    precioMensual: 50.00,
    moneda: 'PEN',
    caracteristicas: [
      'Hasta 5 condominios',
      'Todo lo de Mini',
      'Reportes avanzados',
      'Chat interno',
      'Soporte prioritario',
    ],
  },
  {
    nombre: 'Sentinel Pro',
    slug: 'pro',
    maxCondominios: 12,
    precioMensual: 70.00,
    moneda: 'PEN',
    destacado: true,
    caracteristicas: [
      'Hasta 12 condominios',
      'Todo lo de Start',
      'Nómina completa',
      'PDFs personalizados',
      'Estadísticas avanzadas',
      'Soporte 24/7',
    ],
  },
  {
    nombre: 'Sentinel Max',
    slug: 'max',
    maxCondominios: -1,
    precioMensual: 90.00,
    moneda: 'PEN',
    caracteristicas: [
      'Condominios ilimitados',
      'Todo lo de Pro',
      'API personalizada',
      'Integración contable',
      'Gerente de cuenta dedicado',
    ],
  },
] as const;